root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /tasks
        permanent: true

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

beer:
    resource: "@BeerBundle/Controller/"
    type:     annotation
    prefix:   /



task:
    resource: "@TaskBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

